---
- name: Add hosts info to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_default_ipv4.address }}\t{{ hostvars[item].ansible_hostname }}\t{{ hostvars[item].ansible_nodename }}"
  with_items:
    - "{{ ansible_play_hosts|default([]) }}"

- name: Disable transparent huagepages
  shell: >
    echo 'never' | tee /sys/kernel/mm/transparent_hugepage/enabled &&
    echo 'never' | tee /sys/kernel/mm/transparent_hugepage/defrag

- name: Persist thp disabled at boot
  shell: >
    echo "echo 'never' | tee /sys/kernel/mm/transparent_hugepage/enabled" | tee -a /etc/rc.local &&
    echo "echo 'never' | tee /sys/kernel/mm/transparent_hugepage/defrag" | tee -a /etc/rc.local


- name: Copy ulimit config file to /etc/security/limits.d/
  copy: src=99-mongodb-nproc.conf dest=/etc/security/limits.d/99-mongodb-nproc.conf

- name: Configure sufficient file handles (98000)
  shell: echo 98000 | tee /proc/sys/fs/file-max

- name: Configure sufficient kernel pid limit (64000)
  shell: echo 64000 | tee /proc/sys/kernel/pid_max

- name: Configure sufficient max threads per process (64000)
  shell: echo 64000 | tee /proc/sys/kernel/threads-max

- name: Persist fs.file-max, kernel.pid_max, kernel.threads-max on reboot
  shell: >
    echo "fs.file-max = 98000" | tee -a /etc/sysctl.conf &&
    echo "kernel.pid_max = 64000" | tee -a /etc/sysctl.conf &&
    echo "kernel.threads-max = 64000" | tee -a /etc/sysctl.conf

- name: Set TCP keepalive (120 seconds)
  shell: echo 300 | tee /proc/sys/net/ipv4/tcp_keepalive_time

- name: Persist TCP keepalive setting on reboot
  shell: echo "net.ipv4.tcp_keepalive_time = 300" | tee -a /etc/sysctl.conf
